name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          #terraform_version: "0.12.15"  # O la versión que estés utilizando
          terraform_version: "1.5.0"  # O la versión que estés utilizando

      - name: Terraform init
        run: terraform init -input=false -reconfigure

      - name: Terraform destroy -reconfigure
        #name: Terraform destroy
        run: terraform destroy -auto-approve
